### ISSUE TITLE
SNA status update visuals

### ISSUE THREAD

**Issue by mef** [BrusselsDataScienceCommunity/SNA#3]
I'd like to make the graphs included in the slides of tomorrow's presentation more attractive and viewer-friendly:
- [ ] highlight the parts of the graph that are relevant in the context of the slides
- [ ] prevent text overlaps

The two graphs in question are from the slides 4 (A visualisation of all Belgian meetup groups..) and 5 (A closer look shows that our group is closely related to)

**Comment by mef** [comment]
Question I have is: what are the html files used to generate these two graphs?

**Comment by mathieu1** [comment]
slide 4 (A visualisation of all Belgian meetup groups..) : I'm unsure, doesn't look like anything on github, maybe from http://dataminded.be/projects/datasciencebe/groups/index.html 
slide  5 (A closer look shows that our group is closely related to) : I guess that this is using index_tech.html (which suggests @peeterskris was able to use these html files) and that the "Docker Belgium" neighbour in the presentation is just an artifact from the particular screenshot taken.

**Comment by mef** [comment]
Closing this, I think that the visualizations were fixed for the presentation.
